name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - name: Build
      # https://docs.veracode.com/r/compilation_scala
      run: sbt 'set scalacOptions += "-g:vars"' compile package
    - name: CheckFiles
      run: |
        ls -la */*
